import { createContext, useContext, useState, type ReactNode } from 'react';
import { Language } from '../backend';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  de: {
    // Navigation
    'nav.home': 'Home',
    'nav.domizile': 'Domizile',
    'nav.waldhaus': 'Waldhaus Tannenhof',
    'nav.forsthaus': 'Forsthaus Hirschgrund',
    'nav.fichtenberg': 'Domizil Fichtenberg',
    'nav.schwarzwaldblick': 'Domizil Schwarzwaldblick',
    'nav.faq': 'Häufig gestellte Fragen',
    'nav.reviews': 'Bewertungen',
    'nav.activities': 'Aktivitäten',
    'nav.calendar': 'Verfügbarkeit',
    
    // Home Page
    'home.hero.title': 'Zwischen Wipfeln und Stille',
    'home.hero.subtitle': 'Handverlesene Refugien in den Tiefen des Schwarzwalds – wo uralte Tannen auf zeitlose Eleganz treffen und jeder Atemzug zur Meditation wird.',
    'home.hero.cta': 'Ihr Refugium entdecken',
    'home.intro.title': 'Willkommen in der Waldstille',
    'home.intro.p1': 'Zwischen den majestätischen Tannen des Schwarzwalds und den sanften Hügeln dieser uralten Landschaft liegt eine Welt, in der die Zeit ihren eigenen Rhythmus findet. Der Schwarzwald – eine Region, die seit Jahrhunderten Dichter, Denker und Suchende anzieht. Hier, wo das Licht durch die Baumkronen tanzt und der Wald seine Geschichten flüstert, haben wir vier außergewöhnliche Domizile geschaffen.',
    'home.intro.p2': 'Jedes unserer Häuser ist eine Ode an die Schönheit der Einfachheit. Traditionelle Schwarzwälder Baukunst verschmilzt mit modernem Bewusstsein, natürliche Materialien erzählen von ihrer Herkunft, und jeder Raum öffnet sich zur Waldlandschaft. Mit exklusiven Waldblicken und absoluter Privatsphäre bieten wir Ihnen mehr als einen Urlaub – wir schenken Ihnen Momente der Klarheit, der Verbundenheit, der inneren Ruhe.',
    'home.properties.title': 'Unsere Domizile',
    'home.properties.subtitle': 'Vier Refugien, jedes mit eigener Seele, vereint durch die Liebe zum Wald',
    'home.property.schwarzwaldblick.desc': 'Erhaben über den Baumwipfeln thront dieses Refugium der Exklusivität. Panoramablicke, die den Atem rauben, ein Infinity-Pool, der mit dem Horizont verschmilzt, und eine Stille, die die Seele berührt.',
    'home.property.forsthaus.desc': 'Im Herzen des Waldes, wo die Natur den Rhythmus vorgibt. Ein Ort der Ankunft, wo traditionelle Eleganz auf zeitlose Gastfreundschaft trifft und jeder Morgen mit dem Gesang der Vögel beginnt.',
    'home.property.fichtenberg.desc': 'Architektonische Klarheit trifft auf Waldpoesie. Lichtdurchflutete Räume, die den Blick auf das Wesentliche lenken – ein Refugium für jene, die Schönheit in der Reduktion finden.',
    'home.property.waldhaus.desc': 'Wo Geschichte lebendig wird und Geborgenheit zu Hause ist. Authentische Handwerkskunst, warmes Tannenholz und der Duft von Jahrhunderten – ein Ort, der Wurzeln schlägt im Herzen.',
    'home.property.learnmore': 'Mehr erfahren',
    'home.region.title': 'Die Seele des Schwarzwalds',
    'home.region.text': 'Wandern Sie auf Pfaden, die durch jahrhundertealte Tannenwälder führen. Atmen Sie die klare Waldluft, deren Reinheit Sie spüren können. Entdecken Sie Dörfer, in denen Tradition nicht Museum ist, sondern gelebte Gegenwart. Der Schwarzwald ist keine Kulisse – er ist eine Einladung, wieder zu spüren, was wirklich zählt.',
    'home.region.cta': 'Erlebnisse entdecken',
    'home.reviews.title': 'Stimmen aus dem Refugium',
    'home.review1.text': 'Wir haben viele Orte bereist, doch hier haben wir gefunden, wonach wir nicht wussten, dass wir suchten. Die Waldstille ist nicht leer – sie ist erfüllt von Leben und Schönheit. Jeder Sonnenaufgang war ein Geschenk.',
    'home.review1.author': 'Clara & Johannes M.',
    'home.review1.location': 'Hamburg',
    'home.review2.text': 'Das Forsthaus ist kein Ferienhaus – es ist ein Gefühl. Die Liebe zum Detail, die Qualität der Materialien, die Ruhe im Wald. Wir haben hier nicht nur Urlaub gemacht, wir haben uns selbst wiedergefunden.',
    'home.review2.author': 'Familie Bergmann',
    'home.review2.location': 'Zürich',
    'home.review3.text': 'Selten erlebt man Gastfreundschaft, die so authentisch ist. Das Waldhaus verbindet Tradition mit Komfort auf eine Weise, die berührt. Ein Ort, an den man zurückkehren möchte – immer wieder.',
    'home.review3.author': 'Dr. Elisabeth Steiner',
    'home.review3.location': 'Stuttgart',
    'home.reviews.cta': 'Weitere Erfahrungen lesen',
    'home.contact.title': 'Bereit für Ihre Auszeit?',
    'home.contact.text': 'Lassen Sie uns gemeinsam Ihren perfekten Rückzugsort gestalten. Wir nehmen uns Zeit für Ihre Wünsche und begleiten Sie auf dem Weg zu Ihrem persönlichen Refugium im Schwarzwald.',
    'home.contact.cta': 'Kontakt aufnehmen',
    
    // Property Pages
    'property.gallery': 'Galerie',
    'property.description': 'Beschreibung',
    'property.amenities': 'Ausstattung',
    'property.pricing': 'Preise auf Anfrage',
    'property.inquiry': 'Anfrage senden',
    'property.waldhaus.title': 'Waldhaus Tannenhof',
    'property.waldhaus.desc': 'Wo Geschichte lebendig wird und Geborgenheit zu Hause ist. Authentische Handwerkskunst für bis zu 8 Gäste, eingebettet in unberührte Natur mit privatem Waldblick.',
    'property.forsthaus.title': 'Forsthaus Hirschgrund',
    'property.forsthaus.desc': 'Im Herzen des Waldes, wo die Natur den Rhythmus vorgibt. Traditionelle Eleganz für bis zu 6 Personen mit eigenem Wildbeobachtungspunkt und Panoramaterrasse.',
    'property.fichtenberg.title': 'Domizil Fichtenberg',
    'property.fichtenberg.desc': 'Architektonische Klarheit trifft auf Waldpoesie. Lichtdurchflutetes Refugium für 4 Personen mit bodentiefen Fenstern und minimalistischem Design.',
    'property.schwarzwaldblick.title': 'Domizil Schwarzwaldblick',
    'property.schwarzwaldblick.desc': 'Erhaben über den Baumwipfeln – ein Refugium der Exklusivität. Luxuriöses Anwesen für bis zu 6 Gäste mit Infinity-Pool, privater Sauna und atemberaubendem Panorama.',
    
    // FAQ Page
    'faq.title': 'Häufig gestellte Fragen',
    'faq.subtitle': 'Wir beantworten Ihre wichtigsten Fragen',
    'faq.booking.title': 'Buchung & Reservierung',
    'faq.q1': 'Wie reserviere ich ein Domizil?',
    'faq.a1': 'Nutzen Sie unser Anfrageformular oder kontaktieren Sie uns direkt per E-Mail oder Telefon. Wir melden uns innerhalb von 24 Stunden mit Verfügbarkeiten und einem individuellen Angebot bei Ihnen.',
    'faq.q2': 'Wie weit im Voraus sollte ich buchen?',
    'faq.a2': 'Für die Sommermonate Juni bis September sowie Feiertage empfehlen wir eine Buchung 4-6 Monate im Voraus. Für andere Zeiträume sind auch kurzfristigere Buchungen möglich.',
    'faq.q3': 'Welche Mindestaufenthaltsdauer gilt?',
    'faq.a3': 'Die Mindestaufenthaltsdauer beträgt 3 Nächte. In der Hochsaison (Juli, August, Weihnachten, Ostern) gilt eine Mindestdauer von 7 Nächten. Für das Domizil Schwarzwaldblick beträgt die Mindestdauer ganzjährig 5 Nächte.',
    'faq.arrival.title': 'An- & Abreise',
    'faq.q4': 'Wann kann ich an- und abreisen?',
    'faq.a4': 'Check-in ist ab 15:00 Uhr, Check-out bis 10:00 Uhr. Auf Wunsch und nach Verfügbarkeit können wir auch flexible Zeiten arrangieren. Bitte teilen Sie uns Ihre Wünsche bei der Buchung mit.',
    'faq.q5': 'Wie gelange ich zu den Domizilen?',
    'faq.a5': 'Alle Häuser sind bequem mit dem PKW erreichbar. Von Freiburg sind es etwa 45 Minuten, von Stuttgart 90 Minuten. Detaillierte Anfahrtsbeschreibungen und GPS-Koordinaten erhalten Sie nach Ihrer Buchung. Parkplätze befinden sich direkt am Haus.',
    'faq.amenities.title': 'Ausstattung & Service',
    'faq.q6': 'Was ist in den Domizilen vorhanden?',
    'faq.a6': 'Alle Häuser sind vollständig ausgestattet: hochwertige Küche mit Profi-Geräten, Premium-Bettwäsche und Handtücher, schnelles WLAN, Smart-TV, Waschmaschine, Trockner und vieles mehr. Eine detaillierte Ausstattungsliste senden wir Ihnen gerne zu.',
    'faq.q7': 'Kann ich mit meinem Haustier anreisen?',
    'faq.a7': 'Im Waldhaus Tannenhof und Forsthaus Hirschgrund sind Hunde nach vorheriger Absprache herzlich willkommen (Aufpreis: 25€ pro Nacht). Bitte geben Sie dies bei Ihrer Anfrage an.',
    'faq.q8': 'Welche Services sind inkludiert?',
    'faq.a8': 'Die Endreinigung, Bettwäsche, Handtücher, WLAN und Parkplätze sind im Preis enthalten. Auf Wunsch organisieren wir gerne zusätzliche Services wie Frühstückslieferung, private Köche, Massagen oder E-Bike-Verleih.',
    
    // Reviews Page
    'reviews.title': 'Gästestimmen',
    'reviews.subtitle': 'Erfahrungen aus erster Hand',
    'reviews.unauthorized': 'Nur autorisierte Gäste können eine Bewertung hinterlassen.',
    'reviews.empty': 'Noch keine Bewertungen vorhanden.',
    'reviews.form.show': 'Bewertung schreiben',
    'reviews.form.hide': 'Formular schließen',
    'reviews.form.title': 'Ihre Bewertung',
    'reviews.form.author': 'Ihr Name',
    'reviews.form.author.placeholder': 'z.B. Familie Müller',
    'reviews.form.rating': 'Bewertung',
    'reviews.form.rating.stars': 'Sterne',
    'reviews.form.content': 'Ihre Erfahrung',
    'reviews.form.content.placeholder': 'Teilen Sie Ihre Erfahrungen mit uns...',
    'reviews.form.submit': 'Bewertung absenden',
    'reviews.form.submitting': 'Wird gesendet...',
    'reviews.form.cancel': 'Abbrechen',
    'reviews.form.success': 'Vielen Dank für Ihre Bewertung!',
    'reviews.form.error.required': 'Bitte füllen Sie alle Pflichtfelder aus.',
    'reviews.form.error.submit': 'Fehler beim Absenden. Bitte versuchen Sie es erneut.',
    'reviews.form.token': 'Bewertungs-Token',
    'reviews.form.token.note': 'Bitte geben Sie Ihren Bewertungs-Token ein, den Sie per E-Mail erhalten haben.',
    
    // Activities Page
    'activities.title': 'Erlebnisse',
    'activities.subtitle': 'Entdecken Sie die Vielfalt des Schwarzwalds',
    'activities.nature.title': 'Natur & Bewegung',
    'activities.nature.desc': 'Wandern, Radfahren und Naturerlebnisse in unberührter Waldlandschaft',
    'activities.culture.title': 'Kultur & Genuss',
    'activities.culture.desc': 'Historische Städte, regionale Kulinarik und jahrhundertealte Traditionen',
    'activities.hiking.title': 'Waldwandern',
    'activities.hiking.desc': 'Erkunden Sie Waldpfade von sanften Talwegen bis zu anspruchsvollen Höhenwanderungen. Jeder Schritt offenbart neue Perspektiven auf Täler, Wälder und Gipfel.',
    'activities.cycling.title': 'Radtouren',
    'activities.cycling.desc': 'Entdecken Sie die Region auf zwei Rädern – von gemütlichen Talrundfahrten bis zu sportlichen Mountainbike-Trails durch Wälder und über Höhenzüge.',
    'activities.water.title': 'Naturerlebnisse',
    'activities.water.desc': 'Erleben Sie die Kraft der Natur: Wasserfälle, klare Bäche und mystische Waldlichtungen. Der Schwarzwald offenbart seine Schönheit in jedem Detail.',
    'activities.winter.title': 'Winterzauber',
    'activities.winter.desc': 'Wenn Schnee die Landschaft verwandelt: Skifahren in nahegelegenen Gebieten, Langlaufen durch verschneite Wälder oder Winterwandern in absoluter Stille.',
    'activities.culinary.title': 'Kulinarische Entdeckungen',
    'activities.culinary.desc': 'Genießen Sie regionale Spezialitäten von der Schwarzwälder Stube bis zum Gourmet-Restaurant. Hier schmeckt man die Qualität der Zutaten und die Liebe zum Handwerk.',
    'activities.wellness.title': 'Entspannung & Wellness',
    'activities.wellness.desc': 'Finden Sie innere Ruhe in nahegelegenen Thermen, bei Yoga-Sessions im Wald oder einfach in der heilsamen Stille Ihres privaten Refugiums.',
    
    // Calendar Page
    'calendar.title': 'Verfügbarkeit',
    'calendar.subtitle': 'Planen Sie Ihre Auszeit',
    'calendar.legend': 'Legende',
    'calendar.available': 'Verfügbar',
    'calendar.booked': 'Belegt',
    'calendar.note': 'Diese Übersicht dient zur Orientierung. Für verbindliche Verfügbarkeiten kontaktieren Sie uns bitte direkt – wir beraten Sie gerne persönlich.',
    'calendar.form.title': 'Ihre Buchungsanfrage',
    'calendar.form.name': 'Name',
    'calendar.form.email': 'E-Mail',
    'calendar.form.phone': 'Telefon (optional)',
    'calendar.form.guests': 'Anzahl Gäste',
    'calendar.form.message': 'Nachricht (optional)',
    'calendar.form.message.placeholder': 'Teilen Sie uns Ihre Wünsche mit...',
    'calendar.form.submit': 'Jetzt unverbindlich anfragen',
    'calendar.form.submitting': 'Wird gesendet...',
    'calendar.form.success': 'Vielen Dank für Ihre Anfrage! Wir melden uns innerhalb von 24 Stunden bei Ihnen.',
    'calendar.form.error': 'Leider ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    'calendar.form.error.name': 'Name ist erforderlich',
    'calendar.form.error.email': 'E-Mail ist erforderlich',
    'calendar.form.error.email.invalid': 'Ungültige E-Mail-Adresse',
    'calendar.form.error.validation': 'Bitte überprüfen Sie Ihre Eingaben',
    'calendar.form.person': 'Person',
    'calendar.form.persons': 'Personen',
    
    // Property Page
    'property.subtitle.waldhaus': 'Wo Wurzeln tief reichen',
    'property.tagline.waldhaus': 'Ein Refugium der Geborgenheit, getragen von Geschichte',
    'property.subtitle.forsthaus': 'Wo der Wald den Rhythmus vorgibt',
    'property.tagline.forsthaus': 'Ein Refugium im Herzen der Natur, wo Zeit eine neue Bedeutung erhält',
    'property.subtitle.fichtenberg': 'Wo Klarheit zur Poesie wird',
    'property.tagline.fichtenberg': 'Ein Refugium der Reduktion, wo Licht und Raum tanzen',
    'property.subtitle.schwarzwaldblick': 'Wo Exklusivität zu Hause ist',
    'property.tagline.schwarzwaldblick': 'Ein Refugium erhaben über den Wipfeln, wo Luxus zur Selbstverständlichkeit wird',
    'property.amenities.title': 'Ausstattung & Highlights',
    'property.occupancy.title': 'Belegung & Aufenthalt',
    'property.occupancy.capacity': 'Kapazität',
    'property.occupancy.capacity.value': 'Bis zu {count} Personen',
    'property.occupancy.minstay': 'Mindestaufenthalt',
    'property.occupancy.minstay.value': '{count} Nächte (Hochsaison: 7 Nächte)',
    'property.occupancy.note': 'Preise und Verfügbarkeiten teilen wir Ihnen gerne auf Anfrage mit. Nutzen Sie unser Anfrageformular oder prüfen Sie den Belegungskalender für aktuelle Informationen.',
    'property.occupancy.note.label': 'Hinweis:',
    'property.location.title': 'Lage & Anreise',
    'property.location.region': 'Schwarzwald',
    'property.sidebar.pricing': 'Preise auf Anfrage',
    'property.sidebar.pricing.desc': 'Kontaktieren Sie uns für aktuelle Verfügbarkeiten und individuelle Preisangebote. Wir erstellen Ihnen gerne ein maßgeschneidertes Angebot.',
    'property.sidebar.capacity': 'Kapazität',
    'property.sidebar.minstay': 'Mindestaufenthalt',
    'property.sidebar.minstay.nights': '{count} Nächte',
    'property.sidebar.checkin': 'Check-in',
    'property.sidebar.checkin.time': 'ab 15:00 Uhr',
    'property.sidebar.checkout': 'Check-out',
    'property.sidebar.checkout.time': 'bis 10:00 Uhr',
    'property.sidebar.cta.title': 'Bereit für Ihre Auszeit?',
    'property.sidebar.cta.button': 'Verfügbarkeit prüfen',
    'property.sidebar.contact.title': 'Persönliche Beratung',
    'property.sidebar.contact.phone': 'Telefon:',
    'property.sidebar.contact.email': 'E-Mail:',
    'property.sidebar.contact.note': 'Wir nehmen uns Zeit für Ihre Fragen und beraten Sie gerne persönlich zu diesem Domizil.',
    'property.bottom.title': 'Erleben Sie unvergessliche Momente',
    'property.bottom.desc': 'Lassen Sie sich von der Schönheit des {name} verzaubern. Wir freuen uns darauf, Sie im Schwarzwald willkommen zu heißen.',
    'property.bottom.cta': 'Verfügbarkeit prüfen',
    
    // Footer
    'footer.name': 'Schwarzwald',
    'footer.address': 'Waldweg 7, 79856 Hinterzarten, Deutschland',
    'footer.phone': '+49 7652 91780',
    'footer.email': 'welcome@schwarzwald.at',
    'footer.tagline': 'Handverlesene Refugien in den Tiefen des Schwarzwalds. Wo uralte Tannen auf zeitlose Eleganz treffen.',
    'footer.quick': 'Navigation',
    'footer.legal': 'Rechtliches',
    'footer.impressum': 'Impressum',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'AGB',
    'footer.follow': 'Folgen Sie uns',
    'footer.copyright': '© 2025. Erstellt mit',
    'footer.using': 'mit',
    
    // Common
    'common.loading': 'Lädt...',
    'common.learnmore': 'Mehr erfahren',
    'common.viewdetails': 'Details ansehen',
    'common.required': '*',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.domizile': 'Residences',
    'nav.waldhaus': 'Waldhaus Tannenhof',
    'nav.forsthaus': 'Forsthaus Hirschgrund',
    'nav.fichtenberg': 'Domizil Fichtenberg',
    'nav.schwarzwaldblick': 'Domizil Schwarzwaldblick',
    'nav.faq': 'FAQ',
    'nav.reviews': 'Reviews',
    'nav.activities': 'Activities',
    'nav.calendar': 'Availability',
    
    // Home Page
    'home.hero.title': 'Between Treetops and Silence',
    'home.hero.subtitle': 'Hand-selected refuges in the depths of the Black Forest – where ancient firs meet timeless elegance and every breath becomes meditation.',
    'home.hero.cta': 'Discover Your Refuge',
    'home.intro.title': 'Welcome to Forest Silence',
    'home.intro.p1': 'Between the majestic firs of the Black Forest and the gentle hills of this ancient landscape lies a world where time finds its own rhythm. The Black Forest – a region that has attracted poets, thinkers, and seekers for centuries. Here, where light dances through the canopy and the forest whispers its stories, we have created four extraordinary residences.',
    'home.intro.p2': 'Each of our houses is an ode to the beauty of simplicity. Traditional Black Forest craftsmanship merges with modern consciousness, natural materials tell of their origins, and every room opens to the forest landscape. With exclusive forest views and absolute privacy, we offer you more than a vacation – we give you moments of clarity, connection, and inner peace.',
    'home.properties.title': 'Our Residences',
    'home.properties.subtitle': 'Four refuges, each with its own soul, united by love for the forest',
    'home.property.schwarzwaldblick.desc': 'Elevated above the treetops, this refuge of exclusivity reigns. Panoramic views that take your breath away, an infinity pool merging with the horizon, and a silence that touches the soul.',
    'home.property.forsthaus.desc': 'In the heart of the forest, where nature sets the rhythm. A place of arrival, where traditional elegance meets timeless hospitality and every morning begins with birdsong.',
    'home.property.fichtenberg.desc': 'Architectural clarity meets forest poetry. Light-flooded spaces that direct the gaze to the essential – a refuge for those who find beauty in reduction.',
    'home.property.waldhaus.desc': 'Where history comes alive and comfort feels like home. Authentic craftsmanship, warm fir wood, and the scent of centuries – a place that takes root in the heart.',
    'home.property.learnmore': 'Learn More',
    'home.region.title': 'The Soul of the Black Forest',
    'home.region.text': 'Walk paths that lead through centuries-old fir forests. Breathe the clear forest air whose purity you can feel. Discover villages where tradition is not a museum but lived present. The Black Forest is not a backdrop – it is an invitation to feel again what truly matters.',
    'home.region.cta': 'Discover Experiences',
    'home.reviews.title': 'Voices from the Refuge',
    'home.review1.text': 'We have traveled to many places, but here we found what we didn\'t know we were searching for. The forest silence is not empty – it is filled with life and beauty. Every sunrise was a gift.',
    'home.review1.author': 'Clara & Johannes M.',
    'home.review1.location': 'Hamburg',
    'home.review2.text': 'The Forsthaus is not a holiday home – it is a feeling. The attention to detail, the quality of materials, the peace in the forest. We didn\'t just vacation here, we rediscovered ourselves.',
    'home.review2.author': 'Bergmann Family',
    'home.review2.location': 'Zurich',
    'home.review3.text': 'Rarely does one experience hospitality so authentic. The Waldhaus combines tradition with comfort in a way that touches. A place to return to – again and again.',
    'home.review3.author': 'Dr. Elisabeth Steiner',
    'home.review3.location': 'Stuttgart',
    'home.reviews.cta': 'Read More Experiences',
    'home.contact.title': 'Ready for Your Retreat?',
    'home.contact.text': 'Let us create your perfect retreat together. We take time for your wishes and accompany you on the path to your personal refuge in the Black Forest.',
    'home.contact.cta': 'Get in Touch',
    
    // Property Pages
    'property.gallery': 'Gallery',
    'property.description': 'Description',
    'property.amenities': 'Amenities',
    'property.pricing': 'Prices on Request',
    'property.inquiry': 'Send Inquiry',
    'property.waldhaus.title': 'Waldhaus Tannenhof',
    'property.waldhaus.desc': 'Where history comes alive and comfort feels like home. Authentic craftsmanship for up to 8 guests, nestled in pristine nature with private forest views.',
    'property.forsthaus.title': 'Forsthaus Hirschgrund',
    'property.forsthaus.desc': 'In the heart of the forest, where nature sets the rhythm. Traditional elegance for up to 6 people with private wildlife observation point and panoramic terrace.',
    'property.fichtenberg.title': 'Domizil Fichtenberg',
    'property.fichtenberg.desc': 'Architectural clarity meets forest poetry. Light-flooded refuge for 4 people with floor-to-ceiling windows and minimalist design.',
    'property.schwarzwaldblick.title': 'Domizil Schwarzwaldblick',
    'property.schwarzwaldblick.desc': 'Elevated above the treetops – a refuge of exclusivity. Luxurious estate for up to 6 guests with infinity pool, private sauna, and breathtaking panorama.',
    
    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'We answer your most important questions',
    'faq.booking.title': 'Booking & Reservation',
    'faq.q1': 'How do I reserve a residence?',
    'faq.a1': 'Use our inquiry form or contact us directly via email or phone. We will respond within 24 hours with availability and an individual offer.',
    'faq.q2': 'How far in advance should I book?',
    'faq.a2': 'For summer months June through September and holidays, we recommend booking 4-6 months in advance. For other periods, shorter-notice bookings are also possible.',
    'faq.q3': 'What is the minimum stay requirement?',
    'faq.a3': 'The minimum stay is 3 nights. During high season (July, August, Christmas, Easter), a minimum of 7 nights applies. For Domizil Schwarzwaldblick, the minimum stay is 5 nights year-round.',
    'faq.arrival.title': 'Arrival & Departure',
    'faq.q4': 'When can I check in and out?',
    'faq.a4': 'Check-in is from 3:00 PM, check-out until 10:00 AM. Upon request and subject to availability, we can arrange flexible times. Please share your wishes when booking.',
    'faq.q5': 'How do I reach the residences?',
    'faq.a5': 'All houses are easily accessible by car. From Freiburg it\'s about 45 minutes, from Stuttgart 90 minutes. Detailed directions and GPS coordinates will be provided after booking. Parking is available directly at the house.',
    'faq.amenities.title': 'Amenities & Service',
    'faq.q6': 'What is provided in the residences?',
    'faq.a6': 'All houses are fully equipped: high-quality kitchen with professional appliances, premium bed linen and towels, fast WiFi, Smart TV, washing machine, dryer, and much more. We\'re happy to send you a detailed amenities list.',
    'faq.q7': 'Can I bring my pet?',
    'faq.a7': 'At Waldhaus Tannenhof and Forsthaus Hirschgrund, dogs are warmly welcome upon prior arrangement (surcharge: €25 per night). Please mention this in your inquiry.',
    'faq.q8': 'What services are included?',
    'faq.a8': 'Final cleaning, bed linen, towels, WiFi, and parking are included in the price. Upon request, we gladly arrange additional services such as breakfast delivery, private chefs, massages, or e-bike rentals.',
    
    // Reviews Page
    'reviews.title': 'Guest Testimonials',
    'reviews.subtitle': 'First-hand experiences',
    'reviews.unauthorized': 'Only authorized guests can submit a review.',
    'reviews.empty': 'No reviews yet.',
    'reviews.form.show': 'Write a Review',
    'reviews.form.hide': 'Close Form',
    'reviews.form.title': 'Your Review',
    'reviews.form.author': 'Your Name',
    'reviews.form.author.placeholder': 'e.g. The Smith Family',
    'reviews.form.rating': 'Rating',
    'reviews.form.rating.stars': 'stars',
    'reviews.form.content': 'Your Experience',
    'reviews.form.content.placeholder': 'Share your experience with us...',
    'reviews.form.submit': 'Submit Review',
    'reviews.form.submitting': 'Submitting...',
    'reviews.form.cancel': 'Cancel',
    'reviews.form.success': 'Thank you for your review!',
    'reviews.form.error.required': 'Please fill in all required fields.',
    'reviews.form.error.submit': 'Error submitting. Please try again.',
    'reviews.form.token': 'Review Token',
    'reviews.form.token.note': 'Please enter your review token that you received via email.',
    
    // Activities Page
    'activities.title': 'Experiences',
    'activities.subtitle': 'Discover the diversity of the Black Forest',
    'activities.nature.title': 'Nature & Movement',
    'activities.nature.desc': 'Hiking, cycling, and nature experiences in pristine forest landscapes',
    'activities.culture.title': 'Culture & Enjoyment',
    'activities.culture.desc': 'Historic towns, regional cuisine, and centuries-old traditions',
    'activities.hiking.title': 'Forest Hiking',
    'activities.hiking.desc': 'Explore forest trails from gentle valley paths to challenging ridge hikes. Every step reveals new perspectives on valleys, forests, and peaks.',
    'activities.cycling.title': 'Cycling Tours',
    'activities.cycling.desc': 'Discover the region on two wheels – from leisurely valley circuits to sporty mountain bike trails through forests and over ridges.',
    'activities.water.title': 'Nature Experiences',
    'activities.water.desc': 'Experience the power of nature: waterfalls, clear streams, and mystical forest clearings. The Black Forest reveals its beauty in every detail.',
    'activities.winter.title': 'Winter Magic',
    'activities.winter.desc': 'When snow transforms the landscape: skiing in nearby areas, cross-country skiing through snowy forests, or winter hiking in absolute silence.',
    'activities.culinary.title': 'Culinary Discoveries',
    'activities.culinary.desc': 'Enjoy regional specialties from Black Forest parlors to gourmet restaurants. Here you taste the quality of ingredients and the love of craftsmanship.',
    'activities.wellness.title': 'Relaxation & Wellness',
    'activities.wellness.desc': 'Find inner peace in nearby thermal baths, during yoga sessions in the forest, or simply in the healing silence of your private refuge.',
    
    // Calendar Page
    'calendar.title': 'Availability',
    'calendar.subtitle': 'Plan your retreat',
    'calendar.legend': 'Legend',
    'calendar.available': 'Available',
    'calendar.booked': 'Booked',
    'calendar.note': 'This overview serves as orientation. For binding availability, please contact us directly – we\'re happy to advise you personally.',
    'calendar.form.title': 'Your Booking Inquiry',
    'calendar.form.name': 'Name',
    'calendar.form.email': 'Email',
    'calendar.form.phone': 'Phone (optional)',
    'calendar.form.guests': 'Number of Guests',
    'calendar.form.message': 'Message (optional)',
    'calendar.form.message.placeholder': 'Share your wishes with us...',
    'calendar.form.submit': 'Inquire Now Without Obligation',
    'calendar.form.submitting': 'Submitting...',
    'calendar.form.success': 'Thank you for your inquiry! We will get back to you within 24 hours.',
    'calendar.form.error': 'Unfortunately an error occurred. Please try again.',
    'calendar.form.error.name': 'Name is required',
    'calendar.form.error.email': 'Email is required',
    'calendar.form.error.email.invalid': 'Invalid email address',
    'calendar.form.error.validation': 'Please check your entries',
    'calendar.form.person': 'person',
    'calendar.form.persons': 'people',
    
    // Property Page
    'property.subtitle.waldhaus': 'Where Roots Run Deep',
    'property.tagline.waldhaus': 'A refuge of comfort, carried by history',
    'property.subtitle.forsthaus': 'Where the Forest Sets the Rhythm',
    'property.tagline.forsthaus': 'A refuge in the heart of nature, where time takes on new meaning',
    'property.subtitle.fichtenberg': 'Where Clarity Becomes Poetry',
    'property.tagline.fichtenberg': 'A refuge of reduction, where light and space dance',
    'property.subtitle.schwarzwaldblick': 'Where Exclusivity Is at Home',
    'property.tagline.schwarzwaldblick': 'A refuge elevated above the treetops, where luxury becomes natural',
    'property.amenities.title': 'Amenities & Highlights',
    'property.occupancy.title': 'Occupancy & Stay',
    'property.occupancy.capacity': 'Capacity',
    'property.occupancy.capacity.value': 'Up to {count} people',
    'property.occupancy.minstay': 'Minimum Stay',
    'property.occupancy.minstay.value': '{count} nights (High season: 7 nights)',
    'property.occupancy.note': 'We are happy to share prices and availability upon request. Use our inquiry form or check the booking calendar for current information.',
    'property.occupancy.note.label': 'Note:',
    'property.location.title': 'Location & Directions',
    'property.location.region': 'Black Forest',
    'property.sidebar.pricing': 'Prices on Request',
    'property.sidebar.pricing.desc': 'Contact us for current availability and individual price offers. We are happy to create a tailored offer for you.',
    'property.sidebar.capacity': 'Capacity',
    'property.sidebar.minstay': 'Minimum Stay',
    'property.sidebar.minstay.nights': '{count} nights',
    'property.sidebar.checkin': 'Check-in',
    'property.sidebar.checkin.time': 'from 3:00 PM',
    'property.sidebar.checkout': 'Check-out',
    'property.sidebar.checkout.time': 'until 10:00 AM',
    'property.sidebar.cta.title': 'Ready for Your Retreat?',
    'property.sidebar.cta.button': 'Check Availability',
    'property.sidebar.contact.title': 'Personal Consultation',
    'property.sidebar.contact.phone': 'Phone:',
    'property.sidebar.contact.email': 'Email:',
    'property.sidebar.contact.note': 'We take time for your questions and are happy to advise you personally about this residence.',
    'property.bottom.title': 'Experience Unforgettable Moments',
    'property.bottom.desc': 'Let yourself be enchanted by the beauty of {name}. We look forward to welcoming you to the Black Forest.',
    'property.bottom.cta': 'Check Availability',
    
    // Footer
    'footer.name': 'Schwarzwald',
    'footer.address': 'Waldweg 7, 79856 Hinterzarten, Germany',
    'footer.phone': '+49 7652 91780',
    'footer.email': 'welcome@schwarzwald.at',
    'footer.tagline': 'Hand-selected refuges in the depths of the Black Forest. Where ancient firs meet timeless elegance.',
    'footer.quick': 'Navigation',
    'footer.legal': 'Legal',
    'footer.impressum': 'Imprint',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.follow': 'Follow Us',
    'footer.copyright': '© 2025. Built with',
    'footer.using': 'using',
    
    // Common
    'common.loading': 'Loading...',
    'common.learnmore': 'Learn More',
    'common.viewdetails': 'View Details',
    'common.required': '*',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(Language.de);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.de] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
