/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingInquiry {
  'id' : string,
  'checkIn' : string,
  'name' : string,
  'email' : string,
  'language' : Language,
  'message' : string,
  'timestamp' : bigint,
  'checkOut' : string,
  'phone' : [] | [string],
  'guests' : bigint,
  'roomType' : string,
}
export interface CalendarDay {
  'isSelected' : boolean,
  'date' : string,
  'isAvailable' : boolean,
  'isInRange' : boolean,
}
export interface CalendarMonth {
  'month' : bigint,
  'days' : Array<CalendarDay>,
  'year' : bigint,
}
export interface CalendarState {
  'currentMonth' : CalendarMonth,
  'selectedRange' : DateRange,
}
export interface ContactMessage {
  'id' : string,
  'subject' : string,
  'name' : string,
  'email' : string,
  'language' : Language,
  'message' : string,
  'timestamp' : bigint,
}
export interface DateRange {
  'endDate' : [] | [string],
  'startDate' : [] | [string],
}
export interface Domicile {
  'id' : string,
  'thumbnail' : [] | [string],
  'name' : string,
  'description' : string,
  'rating' : number,
  'reviewCount' : bigint,
}
export interface HouseInfo {
  'id' : string,
  'name' : string,
  'description' : string,
}
export type Language = { 'de' : null } |
  { 'en' : null };
export interface PageContent {
  'title' : string,
  'body' : string,
  'lastUpdated' : bigint,
  'language' : Language,
}
export interface Property {
  'id' : string,
  'minStay' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
  'description' : string,
  'amenities' : Array<string>,
  'language' : Language,
  'capacity' : bigint,
  'location' : string,
  'subtitle' : string,
  'images' : Array<string>,
}
export interface RatingSummary {
  'averageRating' : number,
  'totalReviews' : bigint,
}
export interface Residence {
  'id' : string,
  'reviews' : Array<Review>,
  'name' : string,
  'description' : string,
  'reviewTokens' : Array<ReviewToken>,
}
export interface Review {
  'id' : string,
  'content' : string,
  'author' : string,
  'language' : Language,
  'timestamp' : bigint,
  'residenceId' : string,
  'rating' : bigint,
}
export interface ReviewToken {
  'id' : string,
  'expiresAt' : bigint,
  'email' : string,
  'residenceId' : string,
  'issuedAt' : bigint,
  'isValid' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addOrUpdateDomicile' : ActorMethod<
    [string, string, [] | [string], string, number, bigint],
    string
  >,
  'addOrUpdatePageContent' : ActorMethod<[string, string, Language], string>,
  'addOrUpdateProperty' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<string>,
      bigint,
      bigint,
      string,
      Array<string>,
      Language,
    ],
    string
  >,
  'addOrUpdateResidence' : ActorMethod<[string, string, string], string>,
  'addReview' : ActorMethod<[string, string, bigint, Language, string], string>,
  'addReviewWithToken' : ActorMethod<
    [string, string, string, bigint, Language, string],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearResidenceCalendar' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'generateReviewToken' : ActorMethod<[string, string], string>,
  'getAllBookingInquiries' : ActorMethod<[], Array<BookingInquiry>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllDomiciles' : ActorMethod<[], Array<Domicile>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllResidences' : ActorMethod<[], Array<Residence>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDomicile' : ActorMethod<[string], [] | [Domicile]>,
  'getHousesInfo' : ActorMethod<[], Array<HouseInfo>>,
  'getPageContent' : ActorMethod<[string, Language], [] | [PageContent]>,
  'getProperty' : ActorMethod<[string], [] | [Property]>,
  'getRatingSummaryByResidence' : ActorMethod<[string], RatingSummary>,
  'getResidence' : ActorMethod<[string], [] | [Residence]>,
  'getResidenceCalendar' : ActorMethod<[string], [] | [CalendarState]>,
  'getReviewsByResidence' : ActorMethod<[string], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeDefaultCalendars' : ActorMethod<[], undefined>,
  'initializeDefaultDomiciles' : ActorMethod<[], undefined>,
  'initializeDefaultResidences' : ActorMethod<[], undefined>,
  'invalidateReviewToken' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isValidReviewToken' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingInquiry' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      bigint,
      Language,
    ],
    string
  >,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string, Language],
    string
  >,
  'updateResidenceCalendar' : ActorMethod<
    [string, bigint, bigint, Array<CalendarDay>, DateRange],
    undefined
  >,
  'validateReviewToken' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];