/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Language = IDL.Variant({ 'de' : IDL.Null, 'en' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingInquiry = IDL.Record({
  'id' : IDL.Text,
  'checkIn' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : Language,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'checkOut' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'guests' : IDL.Nat,
  'roomType' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : Language,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Domicile = IDL.Record({
  'id' : IDL.Text,
  'thumbnail' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rating' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});
export const Property = IDL.Record({
  'id' : IDL.Text,
  'minStay' : IDL.Nat,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'language' : Language,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
  'subtitle' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'language' : Language,
  'timestamp' : IDL.Int,
  'residenceId' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewToken = IDL.Record({
  'id' : IDL.Text,
  'expiresAt' : IDL.Int,
  'email' : IDL.Text,
  'residenceId' : IDL.Text,
  'issuedAt' : IDL.Int,
  'isValid' : IDL.Bool,
});
export const Residence = IDL.Record({
  'id' : IDL.Text,
  'reviews' : IDL.Vec(Review),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'reviewTokens' : IDL.Vec(ReviewToken),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HouseInfo = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PageContent = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'language' : Language,
});
export const RatingSummary = IDL.Record({
  'averageRating' : IDL.Float64,
  'totalReviews' : IDL.Nat,
});
export const CalendarDay = IDL.Record({
  'isSelected' : IDL.Bool,
  'date' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'isInRange' : IDL.Bool,
});
export const CalendarMonth = IDL.Record({
  'month' : IDL.Int,
  'days' : IDL.Vec(CalendarDay),
  'year' : IDL.Int,
});
export const DateRange = IDL.Record({
  'endDate' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(IDL.Text),
});
export const CalendarState = IDL.Record({
  'currentMonth' : CalendarMonth,
  'selectedRange' : DateRange,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addOrUpdateDomicile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addOrUpdatePageContent' : IDL.Func(
      [IDL.Text, IDL.Text, Language],
      [IDL.Text],
      [],
    ),
  'addOrUpdateProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        Language,
      ],
      [IDL.Text],
      [],
    ),
  'addOrUpdateResidence' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Language, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addReviewWithToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Language, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearResidenceCalendar' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'generateReviewToken' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllBookingInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllDomiciles' : IDL.Func([], [IDL.Vec(Domicile)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllResidences' : IDL.Func([], [IDL.Vec(Residence)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDomicile' : IDL.Func([IDL.Text], [IDL.Opt(Domicile)], ['query']),
  'getHousesInfo' : IDL.Func([], [IDL.Vec(HouseInfo)], ['query']),
  'getPageContent' : IDL.Func(
      [IDL.Text, Language],
      [IDL.Opt(PageContent)],
      ['query'],
    ),
  'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
  'getRatingSummaryByResidence' : IDL.Func(
      [IDL.Text],
      [RatingSummary],
      ['query'],
    ),
  'getResidence' : IDL.Func([IDL.Text], [IDL.Opt(Residence)], ['query']),
  'getResidenceCalendar' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CalendarState)],
      ['query'],
    ),
  'getReviewsByResidence' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeDefaultCalendars' : IDL.Func([], [], []),
  'initializeDefaultDomiciles' : IDL.Func([], [], []),
  'initializeDefaultResidences' : IDL.Func([], [], []),
  'invalidateReviewToken' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidReviewToken' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBookingInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Language,
      ],
      [IDL.Text],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Language],
      [IDL.Text],
      [],
    ),
  'updateResidenceCalendar' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(CalendarDay), DateRange],
      [],
      [],
    ),
  'validateReviewToken' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Language = IDL.Variant({ 'de' : IDL.Null, 'en' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingInquiry = IDL.Record({
    'id' : IDL.Text,
    'checkIn' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : Language,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'checkOut' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'guests' : IDL.Nat,
    'roomType' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : Language,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Domicile = IDL.Record({
    'id' : IDL.Text,
    'thumbnail' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rating' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  const Property = IDL.Record({
    'id' : IDL.Text,
    'minStay' : IDL.Nat,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'language' : Language,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
    'subtitle' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'language' : Language,
    'timestamp' : IDL.Int,
    'residenceId' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewToken = IDL.Record({
    'id' : IDL.Text,
    'expiresAt' : IDL.Int,
    'email' : IDL.Text,
    'residenceId' : IDL.Text,
    'issuedAt' : IDL.Int,
    'isValid' : IDL.Bool,
  });
  const Residence = IDL.Record({
    'id' : IDL.Text,
    'reviews' : IDL.Vec(Review),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'reviewTokens' : IDL.Vec(ReviewToken),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HouseInfo = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PageContent = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'language' : Language,
  });
  const RatingSummary = IDL.Record({
    'averageRating' : IDL.Float64,
    'totalReviews' : IDL.Nat,
  });
  const CalendarDay = IDL.Record({
    'isSelected' : IDL.Bool,
    'date' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'isInRange' : IDL.Bool,
  });
  const CalendarMonth = IDL.Record({
    'month' : IDL.Int,
    'days' : IDL.Vec(CalendarDay),
    'year' : IDL.Int,
  });
  const DateRange = IDL.Record({
    'endDate' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(IDL.Text),
  });
  const CalendarState = IDL.Record({
    'currentMonth' : CalendarMonth,
    'selectedRange' : DateRange,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addOrUpdateDomicile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addOrUpdatePageContent' : IDL.Func(
        [IDL.Text, IDL.Text, Language],
        [IDL.Text],
        [],
      ),
    'addOrUpdateProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          Language,
        ],
        [IDL.Text],
        [],
      ),
    'addOrUpdateResidence' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Language, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addReviewWithToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Language, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearResidenceCalendar' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'generateReviewToken' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllBookingInquiries' : IDL.Func(
        [],
        [IDL.Vec(BookingInquiry)],
        ['query'],
      ),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllDomiciles' : IDL.Func([], [IDL.Vec(Domicile)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllResidences' : IDL.Func([], [IDL.Vec(Residence)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDomicile' : IDL.Func([IDL.Text], [IDL.Opt(Domicile)], ['query']),
    'getHousesInfo' : IDL.Func([], [IDL.Vec(HouseInfo)], ['query']),
    'getPageContent' : IDL.Func(
        [IDL.Text, Language],
        [IDL.Opt(PageContent)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
    'getRatingSummaryByResidence' : IDL.Func(
        [IDL.Text],
        [RatingSummary],
        ['query'],
      ),
    'getResidence' : IDL.Func([IDL.Text], [IDL.Opt(Residence)], ['query']),
    'getResidenceCalendar' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CalendarState)],
        ['query'],
      ),
    'getReviewsByResidence' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeDefaultCalendars' : IDL.Func([], [], []),
    'initializeDefaultDomiciles' : IDL.Func([], [], []),
    'initializeDefaultResidences' : IDL.Func([], [], []),
    'invalidateReviewToken' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidReviewToken' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBookingInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Language,
        ],
        [IDL.Text],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Language],
        [IDL.Text],
        [],
      ),
    'updateResidenceCalendar' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(CalendarDay), DateRange],
        [],
        [],
      ),
    'validateReviewToken' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };