/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface Review {
    id: string;
    content: string;
    author: string;
    language: Language;
    timestamp: bigint;
    residenceId: string;
    rating: bigint;
}
export interface Residence {
    id: string;
    reviews: Array<Review>;
    name: string;
    description: string;
    reviewTokens: Array<ReviewToken>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CalendarDay {
    isSelected: boolean;
    date: string;
    isAvailable: boolean;
    isInRange: boolean;
}
export interface ReviewToken {
    id: string;
    expiresAt: bigint;
    email: string;
    residenceId: string;
    issuedAt: bigint;
    isValid: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CalendarState {
    currentMonth: CalendarMonth;
    selectedRange: DateRange;
}
export interface BookingInquiry {
    id: string;
    checkIn: string;
    name: string;
    email: string;
    language: Language;
    message: string;
    timestamp: bigint;
    checkOut: string;
    phone?: string;
    guests: bigint;
    roomType: string;
}
export interface CalendarMonth {
    month: bigint;
    days: Array<CalendarDay>;
    year: bigint;
}
export interface Property {
    id: string;
    minStay: bigint;
    name: string;
    lastUpdated: bigint;
    description: string;
    amenities: Array<string>;
    language: Language;
    capacity: bigint;
    location: string;
    subtitle: string;
    images: Array<string>;
}
export interface DateRange {
    endDate?: string;
    startDate?: string;
}
export interface HouseInfo {
    id: string;
    name: string;
    description: string;
}
export interface ContactMessage {
    id: string;
    subject: string;
    name: string;
    email: string;
    language: Language;
    message: string;
    timestamp: bigint;
}
export interface PageContent {
    title: string;
    body: string;
    lastUpdated: bigint;
    language: Language;
}
export interface Domicile {
    id: string;
    thumbnail?: string;
    name: string;
    description: string;
    rating: number;
    reviewCount: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface RatingSummary {
    averageRating: number;
    totalReviews: bigint;
}
export enum Language {
    de = "de",
    en = "en"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addOrUpdateDomicile(id: string, name: string, thumbnail: string | null, description: string, rating: number, reviewCount: bigint): Promise<string>;
    addOrUpdatePageContent(title: string, body: string, language: Language): Promise<string>;
    addOrUpdateProperty(id: string, name: string, subtitle: string, description: string, amenities: Array<string>, capacity: bigint, minStay: bigint, location: string, images: Array<string>, language: Language): Promise<string>;
    addOrUpdateResidence(id: string, name: string, description: string): Promise<string>;
    addReview(author: string, content: string, rating: bigint, language: Language, residenceId: string): Promise<string>;
    addReviewWithToken(tokenId: string, author: string, content: string, rating: bigint, language: Language, residenceId: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearResidenceCalendar(residenceId: string): Promise<void>;
    deleteReview(reviewId: string): Promise<void>;
    generateReviewToken(email: string, residenceId: string): Promise<string>;
    getAllBookingInquiries(): Promise<Array<BookingInquiry>>;
    getAllContactMessages(): Promise<Array<ContactMessage>>;
    getAllDomiciles(): Promise<Array<Domicile>>;
    getAllProperties(): Promise<Array<Property>>;
    getAllResidences(): Promise<Array<Residence>>;
    getAllReviews(): Promise<Array<Review>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDomicile(id: string): Promise<Domicile | null>;
    getHousesInfo(): Promise<Array<HouseInfo>>;
    getPageContent(title: string, language: Language): Promise<PageContent | null>;
    getProperty(id: string): Promise<Property | null>;
    getRatingSummaryByResidence(residenceId: string): Promise<RatingSummary>;
    getResidence(id: string): Promise<Residence | null>;
    getResidenceCalendar(residenceId: string): Promise<CalendarState | null>;
    getReviewsByResidence(residenceId: string): Promise<Array<Review>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    initializeDefaultCalendars(): Promise<void>;
    initializeDefaultDomiciles(): Promise<void>;
    initializeDefaultResidences(): Promise<void>;
    invalidateReviewToken(tokenId: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isValidReviewToken(tokenId: string, residenceId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitBookingInquiry(name: string, email: string, phone: string | null, message: string, checkIn: string, checkOut: string, roomType: string, guests: bigint, language: Language): Promise<string>;
    submitContactMessage(name: string, email: string, subject: string, message: string, language: Language): Promise<string>;
    updateResidenceCalendar(residenceId: string, year: bigint, month: bigint, days: Array<CalendarDay>, selectedRange: DateRange): Promise<void>;
    validateReviewToken(tokenId: string, residenceId: string): Promise<boolean>;
}
import type { BookingInquiry as _BookingInquiry, CalendarMonth as _CalendarMonth, CalendarState as _CalendarState, ContactMessage as _ContactMessage, DateRange as _DateRange, Domicile as _Domicile, Language as _Language, PageContent as _PageContent, Property as _Property, Residence as _Residence, Review as _Review, ReviewToken as _ReviewToken, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addOrUpdateDomicile(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: number, arg5: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateDomicile(arg0, arg1, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateDomicile(arg0, arg1, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async addOrUpdatePageContent(arg0: string, arg1: string, arg2: Language): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdatePageContent(arg0, arg1, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdatePageContent(arg0, arg1, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async addOrUpdateProperty(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: bigint, arg6: bigint, arg7: string, arg8: Array<string>, arg9: Language): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProperty(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProperty(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg9));
            return result;
        }
    }
    async addOrUpdateResidence(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateResidence(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateResidence(arg0, arg1, arg2);
            return result;
        }
    }
    async addReview(arg0: string, arg1: string, arg2: bigint, arg3: Language, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg3), arg4);
            return result;
        }
    }
    async addReviewWithToken(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Language, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReviewWithToken(arg0, arg1, arg2, arg3, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReviewWithToken(arg0, arg1, arg2, arg3, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async clearResidenceCalendar(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearResidenceCalendar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearResidenceCalendar(arg0);
            return result;
        }
    }
    async deleteReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async generateReviewToken(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReviewToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReviewToken(arg0, arg1);
            return result;
        }
    }
    async getAllBookingInquiries(): Promise<Array<BookingInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingInquiries();
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingInquiries();
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllDomiciles(): Promise<Array<Domicile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDomiciles();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDomiciles();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllResidences(): Promise<Array<Residence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResidences();
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResidences();
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDomicile(arg0: string): Promise<Domicile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDomicile(arg0);
                return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDomicile(arg0);
            return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getHousesInfo(): Promise<Array<HouseInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHousesInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHousesInfo();
            return result;
        }
    }
    async getPageContent(arg0: string, arg1: Language): Promise<PageContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageContent(arg0, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg1));
                return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageContent(arg0, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg1));
            return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProperty(arg0: string): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRatingSummaryByResidence(arg0: string): Promise<RatingSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingSummaryByResidence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingSummaryByResidence(arg0);
            return result;
        }
    }
    async getResidence(arg0: string): Promise<Residence | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidence(arg0);
                return from_candid_opt_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidence(arg0);
            return from_candid_opt_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getResidenceCalendar(arg0: string): Promise<CalendarState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidenceCalendar(arg0);
                return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidenceCalendar(arg0);
            return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getReviewsByResidence(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByResidence(arg0);
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByResidence(arg0);
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeDefaultCalendars(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultCalendars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultCalendars();
            return result;
        }
    }
    async initializeDefaultDomiciles(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultDomiciles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultDomiciles();
            return result;
        }
    }
    async initializeDefaultResidences(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultResidences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultResidences();
            return result;
        }
    }
    async invalidateReviewToken(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.invalidateReviewToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.invalidateReviewToken(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isValidReviewToken(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isValidReviewToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isValidReviewToken(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitBookingInquiry(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: Language): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingInquiry(arg0, arg1, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingInquiry(arg0, arg1, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg8));
            return result;
        }
    }
    async submitContactMessage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Language): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0, arg1, arg2, arg3, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0, arg1, arg2, arg3, to_candid_Language_n9(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async updateResidenceCalendar(arg0: string, arg1: bigint, arg2: bigint, arg3: Array<CalendarDay>, arg4: DateRange): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResidenceCalendar(arg0, arg1, arg2, arg3, to_candid_DateRange_n48(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResidenceCalendar(arg0, arg1, arg2, arg3, to_candid_DateRange_n48(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async validateReviewToken(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateReviewToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateReviewToken(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingInquiry_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingInquiry): BookingInquiry {
    return from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_CalendarState_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarState): CalendarState {
    return from_candid_record_n45(uploadFile, downloadFile, value);
}
function from_candid_ContactMessage_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactMessage): ContactMessage {
    return from_candid_record_n21(uploadFile, downloadFile, value);
}
function from_candid_DateRange_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DateRange): DateRange {
    return from_candid_record_n47(uploadFile, downloadFile, value);
}
function from_candid_Domicile_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Domicile): Domicile {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_Language_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n17(uploadFile, downloadFile, value);
}
function from_candid_PageContent_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageContent): PageContent {
    return from_candid_record_n40(uploadFile, downloadFile, value);
}
function from_candid_Property_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Property {
    return from_candid_record_n27(uploadFile, downloadFile, value);
}
function from_candid_Residence_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Residence): Residence {
    return from_candid_record_n30(uploadFile, downloadFile, value);
}
function from_candid_Review_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n33(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Domicile]): Domicile | null {
    return value.length === 0 ? null : from_candid_Domicile_n23(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PageContent]): PageContent | null {
    return value.length === 0 ? null : from_candid_PageContent_n39(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Property | null {
    return value.length === 0 ? null : from_candid_Property_n26(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Residence]): Residence | null {
    return value.length === 0 ? null : from_candid_Residence_n29(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CalendarState]): CalendarState | null {
    return value.length === 0 ? null : from_candid_CalendarState_n44(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    checkIn: string;
    name: string;
    email: string;
    language: _Language;
    message: string;
    timestamp: bigint;
    checkOut: string;
    phone: [] | [string];
    guests: bigint;
    roomType: string;
}): {
    id: string;
    checkIn: string;
    name: string;
    email: string;
    language: Language;
    message: string;
    timestamp: bigint;
    checkOut: string;
    phone?: string;
    guests: bigint;
    roomType: string;
} {
    return {
        id: value.id,
        checkIn: value.checkIn,
        name: value.name,
        email: value.email,
        language: from_candid_Language_n16(uploadFile, downloadFile, value.language),
        message: value.message,
        timestamp: value.timestamp,
        checkOut: value.checkOut,
        phone: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.phone)),
        guests: value.guests,
        roomType: value.roomType
    };
}
function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subject: string;
    name: string;
    email: string;
    language: _Language;
    message: string;
    timestamp: bigint;
}): {
    id: string;
    subject: string;
    name: string;
    email: string;
    language: Language;
    message: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        subject: value.subject,
        name: value.name,
        email: value.email,
        language: from_candid_Language_n16(uploadFile, downloadFile, value.language),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    thumbnail: [] | [string];
    name: string;
    description: string;
    rating: number;
    reviewCount: bigint;
}): {
    id: string;
    thumbnail?: string;
    name: string;
    description: string;
    rating: number;
    reviewCount: bigint;
} {
    return {
        id: value.id,
        thumbnail: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.thumbnail)),
        name: value.name,
        description: value.description,
        rating: value.rating,
        reviewCount: value.reviewCount
    };
}
function from_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    minStay: bigint;
    name: string;
    lastUpdated: bigint;
    description: string;
    amenities: Array<string>;
    language: _Language;
    capacity: bigint;
    location: string;
    subtitle: string;
    images: Array<string>;
}): {
    id: string;
    minStay: bigint;
    name: string;
    lastUpdated: bigint;
    description: string;
    amenities: Array<string>;
    language: Language;
    capacity: bigint;
    location: string;
    subtitle: string;
    images: Array<string>;
} {
    return {
        id: value.id,
        minStay: value.minStay,
        name: value.name,
        lastUpdated: value.lastUpdated,
        description: value.description,
        amenities: value.amenities,
        language: from_candid_Language_n16(uploadFile, downloadFile, value.language),
        capacity: value.capacity,
        location: value.location,
        subtitle: value.subtitle,
        images: value.images
    };
}
function from_candid_record_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    reviews: Array<_Review>;
    name: string;
    description: string;
    reviewTokens: Array<_ReviewToken>;
}): {
    id: string;
    reviews: Array<Review>;
    name: string;
    description: string;
    reviewTokens: Array<ReviewToken>;
} {
    return {
        id: value.id,
        reviews: from_candid_vec_n31(uploadFile, downloadFile, value.reviews),
        name: value.name,
        description: value.description,
        reviewTokens: value.reviewTokens
    };
}
function from_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    author: string;
    language: _Language;
    timestamp: bigint;
    residenceId: string;
    rating: bigint;
}): {
    id: string;
    content: string;
    author: string;
    language: Language;
    timestamp: bigint;
    residenceId: string;
    rating: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        author: value.author,
        language: from_candid_Language_n16(uploadFile, downloadFile, value.language),
        timestamp: value.timestamp,
        residenceId: value.residenceId,
        rating: value.rating
    };
}
function from_candid_record_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    body: string;
    lastUpdated: bigint;
    language: _Language;
}): {
    title: string;
    body: string;
    lastUpdated: bigint;
    language: Language;
} {
    return {
        title: value.title,
        body: value.body,
        lastUpdated: value.lastUpdated,
        language: from_candid_Language_n16(uploadFile, downloadFile, value.language)
    };
}
function from_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentMonth: _CalendarMonth;
    selectedRange: _DateRange;
}): {
    currentMonth: CalendarMonth;
    selectedRange: DateRange;
} {
    return {
        currentMonth: value.currentMonth,
        selectedRange: from_candid_DateRange_n46(uploadFile, downloadFile, value.selectedRange)
    };
}
function from_candid_record_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [string];
    startDate: [] | [string];
}): {
    endDate?: string;
    startDate?: string;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.endDate)),
        startDate: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.startDate))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    de: null;
} | {
    en: null;
}): Language {
    return "de" in value ? Language.de : "en" in value ? Language.en : value;
}
function from_candid_variant_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingInquiry>): Array<BookingInquiry> {
    return value.map((x)=>from_candid_BookingInquiry_n14(uploadFile, downloadFile, x));
}
function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactMessage>): Array<ContactMessage> {
    return value.map((x)=>from_candid_ContactMessage_n20(uploadFile, downloadFile, x));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Domicile>): Array<Domicile> {
    return value.map((x)=>from_candid_Domicile_n23(uploadFile, downloadFile, x));
}
function from_candid_vec_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Array<Property> {
    return value.map((x)=>from_candid_Property_n26(uploadFile, downloadFile, x));
}
function from_candid_vec_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Residence>): Array<Residence> {
    return value.map((x)=>from_candid_Residence_n29(uploadFile, downloadFile, x));
}
function from_candid_vec_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n32(uploadFile, downloadFile, x));
}
function to_candid_DateRange_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DateRange): _DateRange {
    return to_candid_record_n49(uploadFile, downloadFile, value);
}
function to_candid_Language_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n10(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: string;
    startDate?: string;
}): {
    endDate: [] | [string];
    startDate: [] | [string];
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    de: null;
} | {
    en: null;
} {
    return value == Language.de ? {
        de: null
    } : value == Language.en ? {
        en: null
    } : value;
}
function to_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
